# Generated by Django 3.2.20 on 2023-09-24 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mfa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticator",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="authenticator",
            name="last_used_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="authenticator",
            name="type",
            field=models.CharField(
                choices=[
                    ("recovery_codes", "Recovery codes"),
                    ("totp", "TOTP Authenticator"),
                    ("webauthn", "WebAuthn"),
                ],
                max_length=20,
            ),
        ),
    ]
